// <auto-generated />
namespace CinemaTown.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class E22 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(E22));
        
        string IMigrationMetadata.Id
        {
            get { return "202309230050494_E2-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
